#!/bin/bash

# Name of Wi-Fi device is en0
device=en0

# Check status of wi-fi device (is it active or inactive?)
status() {
	# NTD: To check if `print $9` works in all cases
	ip l show enp0s3 | awk '/state/{print $9}'
}

# If wifi is on, turn off after X seconds
isactive() {
        sleep 10
	nmcli networking off
}

# Every 5 seconds, check if wifi is active or inactive
while :; do
        if [ $(status) == UP ]
        then isactive
        fi
        sleep 5
done
